# Generated by Django 4.2.3 on 2023-08-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipe_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('bio', models.TextField(max_length=200, verbose_name='bio')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Foquete'), ('lni-laptop-phone', 'notebookEcelular'), ('lni-cog', 'engrenagem'), ('lni-leaf', 'folha'), ('lni-layers', 'multi')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Servico', 'verbose_name_plural': 'Servicos'},
        ),
    ]
